name: publish-to-npm-and-test-store

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - main
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build libs
        run: pnpm build:libs

      - name: Publish to NPM
        if: "! contains(toJSON(github.event.commits.*.message), '[skip npm]')"
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          VERSION=$(cat version | awk '{$1=$1;print}')
          echo "publish version ${VERSION}"
          pnpm publish --filter "@blocklet/*" --filter --access public --no-git-checks

      - name: Publish to test store
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ai-runtime]')"
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_TEST }}
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-deps: false
          skip-upload: false
          skip-deploy: false
          skip-readme: true
          skip-release: true
          working-directory: blocklets/ai-runtime
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          abtnode-endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          deploy-app-did: zNKq56yExCXmaQpir9nFRu9aPFSYvSoKQr1e
          deploy-mount-point: /ai-runtime

      - name: Deploy to staging server
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ai-studio]')"
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_TEST }}
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-deps: false
          skip-upload: false
          skip-deploy: false
          skip-readme: true
          skip-release: true
          working-directory: blocklets/ai-studio
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          abtnode-endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          deploy-app-did: zNKq56yExCXmaQpir9nFRu9aPFSYvSoKQr1e
          deploy-mount-point: /
